export { runTrials, validateRunOptions, VERSION, DEFAULT_REPEAT, DEFAULT_TIMEOUT_MS } from './run-trials.js';
export { aggregateStatistics } from './statistics.js';
export { assessRun, validatePredicate, DEFAULT_PREDICATE } from './predicates.js';
export { loadRun } from './run-reader.js';
export { compareRuns } from './compare.js';
export type { CompareOptions, ComparisonResult, OutputComparison } from './compare.js';
export { bisectRegression } from './bisect.js';
export type { BisectOptions, BisectResult, BisectCandidate } from './bisect.js';
export { minimizeFailure } from './minimize.js';
export type { MinimizeOptions, MinimizeResult, MinimizeEvaluation, MinimizeFormat } from './minimize.js';
export { createBundle } from './bundle.js';
export type { BundleOptions, BundleResult } from './bundle.js';
export { verifyFix, assessBaselineEligibility } from './verify.js';
export type { VerifyOptions, VerifyResult, VerifyRunEvidence, VerifyContextChange, VerifyChangeField, VerifyAllowedChange, BaselineEligibility } from './verify.js';
export type { ContextCaptureOptions, ContextDeclaration, ContextSnapshot, FileIdentity, RunContext } from './verify-context.js';
export type { RunOptions, RunSummary, RunStatistics, TrialResult, TrialStatus, TerminationReason, FailurePredicate, EnvironmentSnapshot } from './types.js';
